config/routes.rb
Rails.application.routes.draw do

  resources :collections, shallow: true do
    resources :links, except: [:index, :show]
    resources :pictures, except: [:index, :show]
  end

  devise_for :users
  root 'collections#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # guest user (not logged in)
    # can only read shared collections
    unless user
      can :read, Collection, share: true
      return
    end

    # user (logged in)
    # can manage own collections, links and pictures
    can :manage, Collection, user_id: user.id
    can :manage, [Link, Picture], collection: { user_id: user.id }

    # and read read shared collections
    can :read, Collection, share: true
  end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :links, dependent: :destroy
  has_many :pictures, dependent: :destroy

  validates :name, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :collection

  validates :text, presence: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :collection

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :collections, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    if request.xhr?
      render :json => ['You are not authorised to do that.'], :status => :unprocessable_entity
    else
      redirect_to main_app.root_url, :alert => exception.message
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  load_and_authorize_resource

  # GET /collections
  # GET /collections.json
  def index
    unless user_signed_in?
      render 'pages/welcome'
      return
    end
    @collections = current_user.collections
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    authenticate_user! unless @collection.share
    @show_modal=flash[:show_modal]
    # @new_link = @collection.links.build
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params.merge user_id: current_user.id)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      notice='Collection was successfully updated.'
      if collection_params[:share]=='true'
        notice ='Collection was successfully shared.'
        flash[:show_modal]=true
      elsif collection_params[:share]=='false'
        notice ='Collection was successfully unshared.'
      end

      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: notice }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def collection_params
    params.require(:collection).permit(:name, :share)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:edit, :update, :destroy]
  before_action :set_collection, only: [:new, :create]

  before_action :authenticate_user!

  load_and_authorize_resource :collection
  load_and_authorize_resource :link, :through => :collection

  # GET /links/new
  def new
    @link = @collection.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = @collection.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link.collection, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link.collection, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to @link.collection, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:text)
    end

    def set_collection
      @collection = Collection.find params[:collection_id]
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:destroy]
  before_action :set_collection, only: [:new, :create]

  before_action :authenticate_user!

  load_and_authorize_resource :collection
  load_and_authorize_resource :picture, :through => :collection

  # GET /pictures/new
  def new
    @picture = @collection.pictures.build
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @collection.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture.collection, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to @picture.collection, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image) if params[:picture]
    end

    def set_collection
      @collection = Collection.find params[:collection_id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/collections/_form.html.haml
= simple_form_for @collection, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), @collection, :class => 'btn btn-default'

app/views/collections/edit.html.haml
- model_class = Collection
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/collections/index.html.haml
- model_class = Collection
.page-header
  %h1 My collections

%table.table.table-striped
  %tbody
    - @collections.each do |collection|
      %tr
        %td= link_to collection.name, collection_path(collection)
        %td.pull-right
          = link_to t('.destroy', :default => t("helpers.links.destroy")), collection_path(collection), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_collection_path, :class => 'btn btn-primary'

app/views/collections/new.html.haml
- model_class = Collection
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/collections/show.html.haml
- model_class = Collection
.page-header
  %h1= @collection.name
-if can? :manage, @collection
  -if not @collection.share
    =link_to 'Share',collection_path(@collection,collection:{share:true}),method: :patch, class: 'btn btn-primary pull-right'
  -else
    =link_to 'Unshare',collection_path(@collection,collection:{share:false}),method: :patch, class: 'btn btn-default pull-right'

  = link_to t('.back', :default => t("helpers.links.back")), collections_path, :class => 'btn btn-default'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_collection_path(@collection), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), collection_path(@collection), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
  %hr

-# Modal form for shared url.
-if @show_modal
  #temp_information{data: {show_modal: 'true'}}
= content_tag :a, "Modal", href: "#modal", class: 'btn',style: 'display:none;',id: 'show-modal', data: {toggle: 'modal'}
= modal_dialog id: "modal",
  header:{ show_close: true, dismiss: 'modal', title: 'Shared url' },
  body:{ content: request.original_url },
  footer: {  }

%h3 Links
- model_class = Link
%table.table.table-striped
  %tbody
    - @collection.links.each do |link|
      %tr
        %td= link_to link.text,link.text.html_safe, :target => "_blank"
        -if can? :manage, @collection
          %td.pull-right
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_link_path(link), :class => 'btn btn-default btn-xs'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), link_path(link), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
-if can? :manage, @collection
  = link_to 'New link', new_collection_link_path(@collection), :class => 'btn btn-primary'
%hr

%h3 Pictures
.row
  -@collection.pictures.each do |picture|
    .col-xs-12.col-sm-6.col-md-4.picture-cell.thumbnail
      -if can? :manage, @collection
        = link_to t('.destroy', :default => t("helpers.links.destroy")), picture_path(picture), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger delete-button'
      = link_to (image_tag picture.image.url(:medium),class: 'img-responsive'), picture.image.url(:original) , :target => "_blank"

-if can? :manage, @collection
  = link_to 'New picture', new_collection_picture_path(@collection), :class => 'btn btn-primary'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "CollectionKeeper"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body
    = render 'layouts/shared/header'
    .container-fluid
      = bootstrap_flash
      .container-fluid
        = yield
  = debug(params) if Rails.env.development?

app/views/layouts/shared/_header.html.haml
= nav_bar inverse: true, brand: 'CollectionKeeper', responsive: true do
  = menu_group do
    - if user_signed_in?
      =menu_item 'My collections', collections_path
  = menu_group pull: :right do
    - if user_signed_in?
      = menu_item t('.edit_profile'), edit_user_registration_path
      = menu_item t('.log_out'), destroy_user_session_path, method: :delete
    - else
      = menu_item t('.register'), new_user_registration_path
      = menu_item t('.login'), new_user_session_path

app/views/links/_form.html.haml
= simple_form_for([@collection, @link]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :text

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), collection_path(@link.collection), :class => 'btn btn-default'

app/views/links/edit.html.haml
%h1 Editing link

= render 'form'

= link_to 'Show', @link
\|
= link_to 'Back', @link.collection

app/views/links/new.html.haml
%h1 New link

= render 'form'

= link_to 'Back', @collection

app/views/pages/welcome.html.haml
For using this service you must
=link_to 'register', new_user_registration_path
or
=link_to 'log-in', new_user_session_path
first.

app/views/pictures/_form.html.haml
= simple_form_for [@collection, @picture] do |f|
  = f.error_notification

  .form-inputs
    = f.input :image, as: :file

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), collection_path(@picture.collection), :class => 'btn btn-default'

app/views/pictures/new.html.haml
%h1 New picture

= render 'form'

= link_to 'Back', @collection